/*Generado por Disrupsoft*/
package com.planning.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import com.planning.service.ChannelService;
import com.planning.service.PositionService;
import com.planning.util.OracleException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.beans.factory.annotation.Autowired;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wordnik.swagger.annotations.*;
import com.planning.entity.*;
import com.planning.service.*;
import com.planning.util.ArregloCreator;
import com.planning.util.JsonId;
import com.planning.util.RestModelAndView;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

import java.util.ArrayList;

import java.util.List;
import javax.persistence.PersistenceException;

import org.hibernate.exception.SQLGrammarException;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.orm.jpa.JpaSystemException;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.ModelAndView;

/**
 * Controller object for domain model class Channel.
 *
 * @see Channel
 */
@RestController(value = "Planning.ChannelController")
@RequestMapping("/canal")
@Api(description = "Exposes APIs to work with Channel resource.", value = "ChannelController")
public class ChannelController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ChannelController.class);

    @Autowired
    private ChannelService channelService;

    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of Channel instances matching the search criteria.")
    public Page<Channel> findChannels(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Channels list");
        return channelService.findAll(pageable);
    }

    @RequestMapping(value = "/listarCanales", method = {RequestMethod.GET, RequestMethod.POST})
    @ApiOperation(value = "Returns the list of Channel instances.")
    public ModelAndView getChannels(Pageable pageable) {
        LOGGER.debug("Rendering Channels list");
        return new RestModelAndView(canales(channelService.findAll(pageable)));
    }

    @RequestMapping(value = "/listarTodos", method = {RequestMethod.GET, RequestMethod.POST})
    @ApiOperation(value = "Returns the list of Channel instances.")
    public ModelAndView listarTodas(ModelMap map) {
        LOGGER.debug("Rendering Channels list");
        map.put("success", true);
        map.put("canales", channelService.findAll());
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/salvarCanal", method = {RequestMethod.GET, RequestMethod.POST})
    @ApiOperation(value = "Returns the list of Channel instances.")
    public ModelAndView salvarChannel(@RequestBody Channel area, ModelMap map) {
        LOGGER.debug("Rendering Channels list");
        channelService.saveAndFlush(area);
        map.put("success", true);
        map.put("message", "La operación se realizó correctamente");
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/cargarDatos", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the Channel instance associated with the given id.")
    public ModelAndView cargarDatos(@RequestParam("canal_id") Integer id, ModelMap map) {
        Channel area = channelService.findOne(id);
        map.put("success", true);
        map.put("canal", ArregloCreator.cargarChannel(area));
        LOGGER.debug("Channel details with id: {}", area);
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/eliminarCanal", method = RequestMethod.POST)
    @ApiOperation(value = "Deletes the Channel instance associated with the given id.")
    public ModelAndView deleteChannel(@RequestParam("canal_id") Integer id, ModelMap map) {
        LOGGER.debug("Deleting Channel with id: {}", id);
        channelService.delete(id);
        map.put("success", true);
        map.put("message", "La operación se realizó correctamente");
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/eliminarCanales", method = RequestMethod.POST)
    @ApiOperation(value = "Deletes the Channel instance associated with the given id.")
    public ModelAndView eliminarChannels(@RequestBody JsonId ids, ModelMap map) {
        ArrayList<Integer> integers = ids.getIds();
        for (Integer id : integers) {
            channelService.delete(id);
        }
        map.put("success", true);
        map.put("message", "La operación se realizó correctamente");
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the Channel instance associated with the given id.")
    public Channel editChannel(@PathVariable("id") Integer id, @RequestBody Channel instance) {
        LOGGER.debug("Editing Channel with id: {}", instance.getId());
        instance.setId(id);
        instance = channelService.saveAndFlush(instance);
        LOGGER.debug("Channel details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of Channel instances.")
    public Long countAllChannels() {
        LOGGER.debug("counting Channels");
        Long count = channelService.count();
        return count;
    }

    private ModelMap canales(Page<Channel> page) {
        ModelMap map = new ModelMap();
        map.put("sEcho", "1");
        map.put("iTotalRecords", page.getTotalElements());
        map.put("iTotalDisplayRecords", page.getNumberOfElements());
        List<Channel> content = page.getContent();
        ModelMap[] tasks = new ModelMap[content.size()];
        int cont = content.size();
        for (int i = 0; i < cont; i++) {
            tasks[i] = ArregloCreator.crearChannelMap(content.get(i));
        }
        map.put("aaData", tasks);
        return map;
    }

    @ExceptionHandler(Exception.class)
    public ModelAndView tratarExcepcion(Exception e) {
        LOGGER.warn(e.getLocalizedMessage(), e);
        ModelMap modelMap = new ModelMap();
        if (e instanceof JpaSystemException) {
            JpaSystemException jse = (JpaSystemException) e;
            modelMap.put("error", tratarMensaje(jse.getMostSpecificCause()));
        } else if (e instanceof PersistenceException) {
            JpaSystemException exception = new JpaSystemException((PersistenceException) e);
            modelMap.put("error", tratarMensaje(exception.getMostSpecificCause()));
        } else if (e instanceof DataIntegrityViolationException) {
            DataIntegrityViolationException exception = (DataIntegrityViolationException) e;
            modelMap.put("error", tratarMensaje(exception.getMostSpecificCause()));
        } else if (e instanceof SQLGrammarException) {
            SQLGrammarException exception = (SQLGrammarException) e;
            modelMap.put("error", tratarMensaje(exception.getCause()));
        } else {
            OracleException oe = new OracleException(e);
            modelMap.put("error", oe.getMessage());
        }
        modelMap.put("success", false);
        return new RestModelAndView(modelMap);
    }

    private String tratarMensaje(Throwable e) {
        String message = e.getMessage();
        if (e.getMessage().contains("unq_facultad_0")) {
            return "Ya existen estas siglas.";
        } else if (e.getMessage().contains("FK_TASK_CHANNEL")) {
            return "No se puede eliminar este canal porque contiene tareas.";
        } else if (e.getMessage().contains("fk_task_channel")) {
            return "No se puede eliminar este canal porque contiene tareas.";
        }
        OracleException oe = new OracleException(message);
        return oe.getMensaje();
    }

}
