/*Generado por Disrupsoft*/
package com.planning.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import com.planning.service.StatusTaskService;
import com.planning.util.OracleException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.beans.factory.annotation.Autowired;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wordnik.swagger.annotations.*;
import com.planning.entity.*;
import com.planning.util.ArregloCreator;
import com.planning.util.JsonId;
import com.planning.util.RestModelAndView;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.PersistenceException;

import org.hibernate.exception.SQLGrammarException;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.orm.jpa.JpaSystemException;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/**
 * Controller object for domain model class StatusTask.
 *
 * @see StatusTask
 */
@RestController(value = "Planning.StatusTaskController")
@RequestMapping("/estado-tarea")
@Api(description = "Exposes APIs to work with StatusTask resource.", value = "StatusTaskController")
public class StatusTaskController {

    private static final Logger LOGGER = LoggerFactory.getLogger(StatusTaskController.class);

    @Autowired
    private StatusTaskService statusTaskService;

    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of StatusTask instances matching the search criteria.")
    public Page<StatusTask> findStatusTasks(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering StatusTasks list");
        return statusTaskService.findAll(pageable);
    }

    @RequestMapping(value = "/listarEstado", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of StatusTask instances.")
    public ModelAndView listarEstado(Pageable pageable) {
        System.out.println(pageable.getSort());
        LOGGER.debug("Rendering StatusTasks list");
        return new RestModelAndView(estados(statusTaskService.findAll(pageable)));
    }

    @RequestMapping(value = "/listarTodos", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the list of StatusTask instances.")
    public ModelAndView listarTodos(ModelMap map) {
        LOGGER.debug("Rendering StatusTasks list");
        map.put("estados", statusTaskService.findAll());
        map.put("success", true);
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/cargarDatos", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the StatusTask instance associated with the given id.")
    public ModelAndView cargarDatos(@RequestParam("estado_id") Integer id, ModelMap map) {
        StatusTask instance = statusTaskService.findOne(id);
        map.put("success", true);
        map.put("estado", ArregloCreator.crearEstadoTarea(instance));
        LOGGER.debug("StatusTask details with id: {}", instance);
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/eliminarEstado", method = RequestMethod.POST)
    @ApiOperation(value = "Deletes the StatusTask instance associated with the given id.")
    public ModelAndView eliminarEstado(@RequestParam("estado_id") Integer id, ModelMap map) {
        LOGGER.debug("Deleting StatusTask with id: {}", id);
        statusTaskService.delete(id);
        map.put("success", true);
        map.put("message", "La operación se realizó correctamente");
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/eliminarEstados", method = RequestMethod.POST)
    @ApiOperation(value = "Deletes the StatusTask instance associated with the given id.")
    public ModelAndView eliminarEstados(@RequestBody JsonId ids, ModelMap map) {
        ArrayList<Integer> integers = ids.getIds();
        for (Integer id : integers) {
            statusTaskService.delete(id);
        }
        map.put("success", true);
        map.put("message", "La operación se realizó correctamente");
        return new RestModelAndView(map);
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the StatusTask instance associated with the given id.")
    public StatusTask editStatusTask(@PathVariable("id") Integer id, @RequestBody StatusTask instance) throws EntityNotFoundException {
        LOGGER.debug("Editing StatusTask with id: {}", instance.getId());
        instance.setId(id);
        instance = statusTaskService.saveAndFlush(instance);
        LOGGER.debug("StatusTask details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/salvarEstado", method = RequestMethod.POST)
    @ApiOperation(value = "Creates a new StatusTask instance.")
    public ModelAndView salvarEstado(@RequestBody StatusTask instance, ModelMap map) {
        LOGGER.debug("Create StatusTask with information: {}", instance);
        instance = statusTaskService.saveAndFlush(instance);
        LOGGER.debug("Created StatusTask with information: {}", instance);
        map.put("success", true);
        map.put("message", "La operación se realizó correctamente");
        return new RestModelAndView(map);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service
     */
    protected void setStatusTaskService(StatusTaskService service) {
        this.statusTaskService = service;
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of StatusTask instances.")
    public Long countAllStatusTasks() {
        LOGGER.debug("counting StatusTasks");
        Long count = statusTaskService.count();
        return count;
    }

    private ModelMap estados(Page<StatusTask> page) {
        ModelMap map = new ModelMap();
        map.put("sEcho", "1");
        map.put("iTotalRecords", page.getTotalElements());
        map.put("iTotalDisplayRecords", page.getNumberOfElements());
        List<StatusTask> content = page.getContent();
        ModelMap[] tasks = new ModelMap[content.size()];
        int cont = content.size();
        for (int i = 0; i < cont; i++) {
            tasks[i] = ArregloCreator.crearEstadoTareasMap(content.get(i));
        }
        map.put("aaData", tasks);
        return map;
    }

    @ExceptionHandler(Exception.class)
    public ModelAndView tratarExcepcion(Exception e) {
        LOGGER.warn(e.getLocalizedMessage(), e);
        ModelMap modelMap = new ModelMap();
        if (e instanceof JpaSystemException) {
            JpaSystemException jse = (JpaSystemException) e;
            modelMap.put("error", tratarMensaje(jse.getMostSpecificCause()));
        } else if (e instanceof PersistenceException) {
            JpaSystemException exception = new JpaSystemException((PersistenceException) e);
            modelMap.put("error", tratarMensaje(exception.getMostSpecificCause()));
        } else if (e instanceof DataIntegrityViolationException) {
            DataIntegrityViolationException exception = (DataIntegrityViolationException) e;
            modelMap.put("error", tratarMensaje(exception.getMostSpecificCause()));
        } else if (e instanceof SQLGrammarException) {
            SQLGrammarException exception = (SQLGrammarException) e;
            modelMap.put("error", tratarMensaje(exception.getCause()));
        } else {
            OracleException oe = new OracleException(e);
            modelMap.put("error", oe.getMessage());
        }
        modelMap.put("success", false);
        return new RestModelAndView(modelMap);
    }

    private String tratarMensaje(Throwable e) {
        String message = e.getMessage();
        if (e.getMessage().contains("unq_facultad_0")) {
            return "Ya existen estas siglas.";
        } else if (e.getMessage().contains("fk_status_task")) {
            return "No se puede eliminar este estado porque contiene tareas.";
        } else if (e.getMessage().contains("fkd63y39p15lp39yjvbei8wvogl")) {
            return "No se puede eliminar este estado porque contiene tareas.";
        } else if (e.getMessage().contains("fkd63y39p15lp39yjvbei8wvogl")) {
            return "No se puede eliminar este estado porque contiene tareas.";
        } else if (e.getMessage().contains("FK_PLTASK_STATUSTASK")) {
            return "No se puede eliminar este estado porque contiene tareas de planes.";
        } else if (e.getMessage().contains("FK_STATUS_TASK")) {
            return "No se puede eliminar este estado porque contiene tareas.";
        } else if (e.getMessage().contains("fk_departamento_id_facultad")) {
            return "No se puede eliminar esta facultad porque contiene departamentos.";
        }
        OracleException oe = new OracleException(message);
        return oe.getMensaje();
    }

}
