/*Generado por Disrupsoft*/
package com.planning.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import com.planning.entity.Document;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Set;

/**
 * Service object for domain model class Document.
 *
 * @see Document
 */
public interface DocumentService extends JpaRepository<Document, Integer> {
    
    public List<Document> findByUltimo(boolean ultimo);
    
    public List<Document> findByTaskId(Integer id);
    
    public Set<Document> findByIdContaining(List<Integer> ids);
}
