/*Generado por Disrupsoft*/
package com.planning.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import com.planning.entity.Notificacion;
import com.planning.entity.Position;
import com.planning.entity.StatusTask;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * Service object for domain model class StatusTask.
 *
 * @see StatusTask
 */
public interface NotificacionService extends JpaRepository<Notificacion, Long> {
    
    public List<Notificacion> findByLeido(boolean leido);
    
    public List<Notificacion> findByPositionAndLeido(Position position, boolean leido);
    
    public Long countByPositionAndLeido(Position position, boolean leido);
}
